### ISSUE TITLE
"Craft anywhere an error occured. Check log for any additional information"

### ISSUE THREAD

**Issue by Blitz1216** [elenakrittik/CraftAnywhere#1]
Hello! First, we love the mod! We have been playing a full 2 weeks now and out of nowhere we got a small crash and now my wife cannot craft anywhere but I can. We have updated everything and reinstalled the mod with no success. I am not sure how to check the logs for this particular issue—mostly looking for possible fixes or workarounds.

Thank you and have a great day!

Email:Bbaylot1216@gmail.com

**Comment by elenakrittik** [comment]
Hello! This message most likely means that you are too far from the HUB (and therefore the mod can't access it's integrated workbench) and there are no nearby "standalone" workbenches either. Please ensure that there is at least one workbench near you, and if the problem remains, send me the log file (called "`FactoryGame.log`") located in "`C:\Users\<your username here>\AppData\Local\FactoryGame\Saved\Logs\`". Thanks for using the mod!

**Comment by elenakrittik** [comment]
Resolved via email, looks like there were problems due to other mods.
